import type { Metadata } from "next";
import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";

// Import font Poppins tanpa menggunakan variable
const pf = Noto_Sans_Georgian({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Tambahkan berat font yang diperlukan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pf.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
